In [4]:
import os
import cv2
import numpy as np
from sklearn import linear_model
from sklearn import preprocessing

train_path = r'C:\Users\nickp\OneDrive\Documents\class\cs520\Assignment 4\assignment4\train images'
test_path = r'C:\Users\nickp\OneDrive\Documents\class\cs520\Assignment 4\assignment4\test images\test02.jpeg'

In [2]:
train_images = [f for f in os.listdir(train_path) if os.path.isfile(os.path.join(train_path, f))]

# Train

In [8]:
X = []
yr,yg,yb = [],[],[]

for img in train_images:
    
    img_path = os.path.join(train_path, img)
    gray_img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
    color_img = cv2.imread(img_path, cv2.IMREAD_COLOR)

    for i in range(color_img.shape[0]):
        for j in range(color_img.shape[1]):
            
            # get data from surrounding pixels
            SURROUNDING = [(i-1, j-1), (i-1, j), (i-1,j+1),(i, j-1),
                           (i, j), (i,j+1),(i+1, j-1), (i+1, j), (i+1,j+1)]
            pixels = []
            for n, m in SURROUNDING:
                if ((0 <= n <= gray_img.shape[0]-1) 
                    and (0 <= m <= gray_img.shape[1]-1)):
                    pixels.append(gray_img[n,m])
                else:
                    pixels.append(gray_img[i,j])
                    
            X.append(pixels)
            yr.append([color_img[i,j,0].tolist()])
            yg.append([color_img[i,j,1].tolist()])
            yb.append([color_img[i,j,2].tolist()])
            
X = np.array(X)
yr = np.array(yr).reshape(-1)
yg = np.array(yg).reshape(-1)
yb = np.array(yb).reshape(-1)

red = linear_model.LinearRegression().fit(X,yr);
green = linear_model.LinearRegression().fit(X,yg);
blue = linear_model.LinearRegression().fit(X,yb);

In [9]:
red.coef_

array([ 4.61757357e-03, -9.17794196e-04, -2.55062815e-03, -2.55565915e-02,
        9.61279873e-01, -2.63153773e-02,  3.97873726e-02,  2.35625987e-02,
        8.53389685e-03])

# Test

In [5]:
img = cv2.imread(test_path, cv2.IMREAD_GRAYSCALE)
colored_img = np.zeros((img.shape[0],img.shape[1],3))

for i in range(img.shape[0]):
    for j in range(img.shape[1]):

        # get data from surrounding pixels
        SURROUNDING = [
            (i-1, j-1), (i-1, j), (i-1,j+1),
            (i, j-1), (i, j), (i,j+1), 
            (i+1, j-1), (i+1, j), (i+1,j+1)
        ]
        pixels = []
        for n, m in SURROUNDING:

            if (0 <= n <= img.shape[0]-1) and (0 <= m <= img.shape[1]-1):
                pixels.append(img[n,m])
            else:
                pixels.append(img[i,j])

        r = red.predict(np.array(pixels).reshape(1,-1))
        g = blue.predict(np.array(pixels).reshape(1,-1))
        b = green.predict(np.array(pixels).reshape(1,-1))
        colored_img[i,j,0] = int(r)
        colored_img[i,j,1] = int(g)
        colored_img[i,j,2] = int(b)

cv2.imwrite('colorized.png',colored_img)

True

# Train

In [6]:
ploy = preprocessing.PolynomialFeatures(degree=3, include_bias=False)
Xnew = ploy.fit_transform(X)
red = linear_model.LinearRegression().fit(Xnew,yr);
green = linear_model.LinearRegression().fit(Xnew,yg);
blue = linear_model.LinearRegression().fit(Xnew,yb);

# Test

In [7]:
img = cv2.imread(test_path, cv2.IMREAD_GRAYSCALE)
colored_img = np.zeros((img.shape[0],img.shape[1],3))

for i in range(img.shape[0]):
    for j in range(img.shape[1]):

        # get data from surrounding pixels
        SURROUNDING = [
            (i-1, j-1), (i-1, j), (i-1,j+1),
            (i, j-1), (i, j), (i,j+1), 
            (i+1, j-1), (i+1, j), (i+1,j+1)
        ]
        pixels = []
        for n, m in SURROUNDING:

            if (0 <= n <= img.shape[0]-1) and (0 <= m <= img.shape[1]-1):
                pixels.append(img[n,m])
            else:
                pixels.append(img[i,j])

        dat = ploy.fit_transform(np.array(pixels).reshape(1, -1))

        r = red.predict(dat.reshape(1,-1))
        g = green.predict(dat.reshape(1,-1))
        b = blue.predict(dat.reshape(1,-1))
        
        colored_img[i,j,0] = int(r)
        colored_img[i,j,1] = int(g)
        colored_img[i,j,2] = int(b)

cv2.imwrite('colorized2.png',colored_img)

True

# Train

In [9]:
red = linear_model.Ridge().fit(X,yr);
green = linear_model.Ridge().fit(X,yg);
blue = linear_model.Ridge().fit(X,yb);

In [10]:
red.coef_

array([ 4.61757064e-03, -9.17788537e-04, -2.55062887e-03, -2.55565874e-02,
        9.61279862e-01, -2.63153734e-02,  3.97873716e-02,  2.35626044e-02,
        8.53389394e-03])

In [11]:
green.coef_

array([ 3.83631932e-03, -1.88565970e-03,  3.62460920e-03, -5.69922673e-04,
        9.99794127e-01, -3.71971294e-03,  1.00866317e-02, -1.50387184e-03,
        1.93901101e-02])

In [12]:
blue.coef_

array([-6.73586193e-03,  1.03733570e-02,  1.75673205e-04,  5.06437044e-03,
        9.92641776e-01,  1.19458900e-02, -2.67820504e-02,  1.92225554e-04,
       -3.73584741e-02])

In [13]:
img = cv2.imread(test_path, cv2.IMREAD_GRAYSCALE)
colored_img = np.zeros((img.shape[0],img.shape[1],3))

for i in range(img.shape[0]):
    for j in range(img.shape[1]):

        # get data from surrounding pixels
        SURROUNDING = [
            (i-1, j-1), (i-1, j), (i-1,j+1),
            (i, j-1), (i, j), (i,j+1), 
            (i+1, j-1), (i+1, j), (i+1,j+1)
        ]
        pixels = []
        for n, m in SURROUNDING:

            if (0 <= n <= img.shape[0]-1) and (0 <= m <= img.shape[1]-1):
                pixels.append(img[n,m])
            else:
                pixels.append(img[i,j])

        r = red.predict(np.array(pixels).reshape(1,-1))
        g = blue.predict(np.array(pixels).reshape(1,-1))
        b = green.predict(np.array(pixels).reshape(1,-1))
        colored_img[i,j,0] = int(r)
        colored_img[i,j,1] = int(g)
        colored_img[i,j,2] = int(b)

cv2.imwrite('colorized3.png',colored_img)

True

In [14]:
from sklearn.linear_model import ElasticNet

In [ ]:
red = ElasticNet(random_state=0).fit(Xnew, yr)
blue = ElasticNet(random_state=0).fit(Xnew, yb)
green = ElasticNet(random_state=0).fit(Xnew, yg)

In [ ]:
red.coef_

In [ ]:
img = cv2.imread(test_path, cv2.IMREAD_GRAYSCALE)
colored_img = np.zeros((img.shape[0],img.shape[1],3))

for i in range(img.shape[0]):
    for j in range(img.shape[1]):

        # get data from surrounding pixels
        SURROUNDING = [
            (i-1, j-1), (i-1, j), (i-1,j+1),
            (i, j-1), (i, j), (i,j+1), 
            (i+1, j-1), (i+1, j), (i+1,j+1)
        ]
        pixels = []
        for n, m in SURROUNDING:

            if (0 <= n <= img.shape[0]-1) and (0 <= m <= img.shape[1]-1):
                pixels.append(img[n,m])
            else:
                pixels.append(img[i,j])

        dat = ploy.fit_transform(np.array(pixels).reshape(1, -1))

        r = red.predict(dat.reshape(1,-1))
        g = green.predict(dat.reshape(1,-1))
        b = blue.predict(dat.reshape(1,-1))
        
        colored_img[i,j,0] = int(r)
        colored_img[i,j,1] = int(g)
        colored_img[i,j,2] = int(b)

cv2.imwrite('colorized3.png',colored_img)